# Generated by Django 3.0.7 on 2020-06-29 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Contact',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=30)),
                        ('email', models.EmailField(default='your@email.com', max_length=254)),
                        ('message_body', models.TextField()),
                        ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M')),
                        ('phone', models.CharField(default='+1-234-5678', max_length=30)),
                    ],
                    options={
                        'db_table': 'portfolio_contact',
                    },
                ),
                migrations.CreateModel(
                    name='Review',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=30)),
                        ('email', models.EmailField(default='your@email.com', max_length=254)),
                        ('message_body', models.TextField()),
                        ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M')),
                    ],
                    options={
                        'db_table': 'portfolio_review',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
