# Generated by Django 3.0.7 on 2020-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254, verbose_name='Your email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_body',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='+1-234-5678', max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254, verbose_name='Your email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message_body',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Your name'),
        ),
    ]
