# Generated by Django 3.0.7 on 2020-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='no@no.com', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='review_body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
