# Generated by Django 3.0.7 on 2020-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_review_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(default='+1-234-5678', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
    ]
