# Generated by Django 3.0.7 on 2020-06-17 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200616_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M'),
        ),
    ]
