# Generated by Django 3.0.7 on 2020-06-19 21:02

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200617_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[1200, 800], upload_to='images/carousel/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
