# Generated by Django 3.0.7 on 2020-06-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_carousel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Contact',
                ),
                migrations.DeleteModel(
                    name='Review',
                ),
            ],
            database_operations=[]
        ),
    ]
