# Generated by Django 3.0.7 on 2020-07-20 11:50

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200629_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='category name')),
                ('slug', models.SlugField(verbose_name='address on site')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[1200, 800], upload_to='gallery/img/photos', verbose_name='photo')),
                ('parent', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.Category', verbose_name='category')),
            ],
        ),
        migrations.DeleteModel(
            name='Portrait',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.DeleteModel(
            name='Wedding',
        ),
    ]
