# Generated by Django 3.0.7 on 2020-07-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='No name', max_length=64, verbose_name='photo name'),
        ),
    ]
